{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "561dda5a-2f96-4250-808f-9dd254266fb5",
   "metadata": {},
   "outputs": [],
   "source": [
    "class GradientLayer(tf.keras.layers.Layer):\n",
    "    \"\"\"\n",
    "    Custom layer to compute derivatives for the steady Navier-Stokes equation.\n",
    "    \n",
    "    This layer computes the stream function (psi), pressure (p), and their derivatives\n",
    "    up to second order using automatic differentiation.\n",
    "    \n",
    "    Attributes:\n",
    "        model: keras network model that predicts psi and p from (x,y) coordinates\n",
    "    \"\"\"\n",
    "    \n",
    "    def __init__(self, model, **kwargs):\n",
    "        \"\"\"\n",
    "        Initialize the GradientLayer.\n",
    "        \n",
    "        Args:\n",
    "            model: keras network model that predicts psi and p\n",
    "            **kwargs: additional layer arguments\n",
    "        \"\"\"\n",
    "        self.model = model\n",
    "        super().__init__(**kwargs)\n",
    "\n",
    "    def call(self, xy):\n",
    "        \"\"\"\n",
    "        Compute derivatives for the steady Navier-Stokes equation.\n",
    "        \n",
    "        Args:\n",
    "            xy: input tensor with shape (batch_size, 2) containing (x,y) coordinates\n",
    "            \n",
    "        Returns:\n",
    "            psi: stream function\n",
    "            p_grads: tuple containing (p, p_x, p_y)\n",
    "            u_grads: tuple containing (u, u_x, u_y, u_xx, u_yy)\n",
    "            v_grads: tuple containing (v, v_x, v_y, v_xx, v_yy)\n",
    "        \"\"\"\n",
    "        x, y = xy[..., 0:1], xy[..., 1:2]  # Split into x and y components\n",
    "        \n",
    "        # Use nested gradient tapes to compute higher-order derivatives\n",
    "        with tf.GradientTape(persistent=True) as ggg:\n",
    "            ggg.watch([x, y])\n",
    "            with tf.GradientTape(persistent=True) as gg:\n",
    "                gg.watch([x, y])\n",
    "                with tf.GradientTape(persistent=True) as g:\n",
    "                    g.watch([x, y])\n",
    "                    psi_p = self.model(tf.concat([x, y], axis=-1))\n",
    "                    psi = psi_p[..., 0:1]\n",
    "                    p = psi_p[..., 1:2]\n",
    "                # First derivatives\n",
    "                u = g.batch_jacobian(psi, y)[..., 0]\n",
    "                v = -g.batch_jacobian(psi, x)[..., 0]\n",
    "                p_x = g.batch_jacobian(p, x)[..., 0]\n",
    "                p_y = g.batch_jacobian(p, y)[..., 0]\n",
    "                del g\n",
    "            # Second derivatives\n",
    "            u_x = gg.batch_jacobian(u, x)[..., 0]\n",
    "            u_y = gg.batch_jacobian(u, y)[..., 0]\n",
    "            v_x = gg.batch_jacobian(v, x)[..., 0]\n",
    "            v_y = gg.batch_jacobian(v, y)[..., 0]\n",
    "            del gg\n",
    "        # Third derivatives\n",
    "        u_xx = ggg.batch_jacobian(u_x, x)[..., 0]\n",
    "        u_yy = ggg.batch_jacobian(u_y, y)[..., 0]\n",
    "        v_xx = ggg.batch_jacobian(v_x, x)[..., 0]\n",
    "        v_yy = ggg.batch_jacobian(v_y, y)[..., 0]\n",
    "        del ggg\n",
    "\n",
    "        p_grads = (p, p_x, p_y)\n",
    "        u_grads = (u, u_x, u_y, u_xx, u_yy)\n",
    "        v_grads = (v, v_x, v_y, v_xx, v_yy)\n",
    "\n",
    "        return psi, p_grads, u_grads, v_grads"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
